name: nullable_absent
description: Absent value for nullable field
version: 1.0.0
repository: https://github.com/chalermpong/dart_nullable_absent

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
