name: nullable_absent
description: Absent value for nullable field
version: 1.0.1
repository: https://github.com/chalermpong/dart_nullable_absent

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

issue_tracker: https://github.com/chalermpong/dart_nullable_absent/issues

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
